name: Snapshot Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  snapshot:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Select Xcode version
        run: sudo xcode-select -s /Applications/Xcode_15.2.app

      - name: Install SnapshotTesting if needed
        run: |
          if [ -f "Podfile" ]; then
            sudo gem install cocoapods
            pod install
          fi

      - name: Run Snapshot Tests
        run: |
          xcodebuild test \
            -project PhotoQRLogger.xcodeproj \
            -scheme PhotoQRLogger \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.4' \
            ONLY_ACTIVE_ARCH=YES | xcpretty